version: '3.9'

services:
  db:
    restart: always
    image: postgres:14.7-alpine
    container_name: smit_db
    env_file:
      - ./src/core/.env.docker
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d smit_database" ]
      interval: 5s
      timeout: 5s
      retries: 5
  service:
    build: .
    container_name: smit_service
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8008:8000'
    volumes:
      - ./src/core/.env.docker:/app/src/core/.env
  redis:
    image: redis/redis-stack:latest
    container_name: smit_redis
    expose:
      - '6379'
      - '8001'
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data: